/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CxProlog */

#ifndef _Included_CxProlog
#define _Included_CxProlog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CxProlog
 * Method:    NotifyProlog
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CxProlog_NotifyProlog
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
